version: "3.8"
services:
# mongo:
  #   image: mongo:latest
  #   restart: always
  #   container_name: flask-docker
  #   hostname: host-mongo
  #   enviroments:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: secret
  #   volumes:
  #     - ./data:/data/db
  #     - ./data/log:/var/log/mogodb/
  #   ports:
  #     - "27017:27017"

  website:
    build: ./
    ports:
      - 5000:80
    container_name: website
  